server:
  port: 8080

spring:
  application:
    name: websocket-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://127.0.0.1:9000}

  artemis:
    mode: native
    broker-url: ${ARTEMIS_BROKER_URL:tcp://192.168.1.210:9876}
    user: admin
    password: secret

jms:
  messaging:
    topic: /messaging-topic-shared
